services:
  - type: web
    name: subs
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20.12.2
      - key: DATABASE_URL
        sync: false
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: PUBLIC_BASE_URL
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true
